# POS Agent - Config

# HTTP Server Port
http.port=8081

# Unique identifier for this POS station
station.id=1f6ea8e1-1c10-4a79-939e-a44bd96eed4f

# Printer
#printer.name=EPSON TM-T88V Receipt5
printer.path=/dev/usb/lp5

#printer.network_ip=192.168.1.100
printer.network_ip=192.168.68.51
printer.port=9100

# Business
business.name=Tequila SAAS
business.address=Tequila, Jalisco
business.phone=000-000-0000

# Scale
#scale.port=COM3
scale.port=/dev/ttyACM0
scale.enabled=false
scale.autoConnect=true

# SaaS Heartbeat
saas.api.url=https://api.ventacore.app/api/v1
agent.api.key=default-agent-secret