# POS Printer Agent - Config

# HTTP Server Port
http.port=8081

# Unique identifier for this POS station
station.id=POS1

# Printer
#printer.name=EPSON TM-T88V Receipt5
printer.path=/dev/usb/lp5

# Business
business.name=LA PASADITA
business.address=Morelos #124 Col. Centro C.P. 46400
business.phone=374 104 3536

# Scale
#scale.port=COM3
scale.port=/dev/ttyACM0
scale.enabled=true
scale.autoConnect=true